### ISSUE TITLE
Seeing issues after upgrading to 0.12.5

### ISSUE THREAD

**Issue by trumpet2012** [ghazi-git/drf-standardized-errors#37]
After upgrading this library to `0.12.5` we are unable to generate our schema provided through the `django-spectacular` library.

We are seeing this issue: **'list' object has no attribute 'items'**
![image](https://user-images.githubusercontent.com/6753326/221989928-4c133afc-4f0b-43ab-a8d1-d812a3959d4e.png)

View of the stack showing the object that is expected to be a dict actually being a list.
![image](https://user-images.githubusercontent.com/6753326/221988481-9da020ff-ecd6-4836-b20b-494eeebbcecb.png)

Full stack trace:
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/schema/

Django Version: 4.1.7
Python Version: 3.9.14

Traceback (most recent call last):
  File "/workspace/backend/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 85, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/workspace/backend/.venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_spectacular/views.py", line 82, in get
    return self._get_schema_response(request)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_spectacular/views.py", line 90, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_spectacular/utils.py", line 364, in get_operation
    return super().get_operation(path, path_regex, path_prefix, method, registry)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_spectacular/openapi.py", line 94, in get_operation
    operation['responses'] = self._get_response_bodies()
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_standardized_errors/openapi.py", line 59, in _get_response_bodies
    serializer = self._get_error_response_serializer(status_code)
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_standardized_errors/openapi.py", line 246, in _get_error_response_serializer
    return self._get_http400_serializer()
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_standardized_errors/openapi.py", line 268, in _get_http400_serializer
    serializer = self._get_serializer_for_validation_error_response()
  File "/opt/project/backend/src/schema/openapi.py", line 37, in _get_serializer_for_validation_error_response
    return get_validation_error_serializer(
  File "/workspace/backend/.venv/lib/python3.9/site-packages/drf_standardized_errors/openapi_utils.py", line 397, in get_validation_error_serializer
    for field_name, error_codes in error_codes_by_field.items()

Exception Type: AttributeError at /schema/
Exception Value: 'list' object has no attribute 'items'
```

Current workaround: Downgrading to 0.12.4 bypasses the issue.

**Comment by trumpet2012** [comment]
Looking through the recent changes, it looks like https://github.com/ghazi-git/drf-standardized-errors/commit/dadfb328f68f24e8ba218901b1752c1e0ddc6b23 may be when this was introduced.

**Comment by trumpet2012** [comment]
This issue was due to using a custom `ErrorAutoSchema` that wasn't calling through to the super of `_get_serializer_for_validation_error_response`.

Apologies for the noise. Thanks for the great package!
